export const initialValue = {
  likes: "",
  comments: "",
  commentlikes: "",
  likeonphoto: "",
  followrequest: "",
  friends: "",
  directrequest: "",
  instadirect: "",
  reminder: "",
  firstpost: "",
  tvview: "",
  supportrequest: "",
  livevideo: "",
};
